onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /bench/iCLK_50
add wave -noupdate /bench/iKey
add wave -noupdate /bench/pic_int_i
add wave -noupdate /bench/clk
add wave -noupdate /bench/rst
add wave -noupdate /bench/wb_rst
add wave -noupdate /bench/dahb_clk_i
add wave -noupdate /bench/dahb_rstn_i
add wave -noupdate /bench/dahb_addr_o
add wave -noupdate /bench/dahb_trans_o
add wave -noupdate /bench/dahb_write_o
add wave -noupdate /bench/dahb_size_o
add wave -noupdate /bench/dahb_burst_o
add wave -noupdate /bench/dahb_prot_o
add wave -noupdate /bench/dahb_wdata_o
add wave -noupdate /bench/dahb_rdata_i
add wave -noupdate /bench/dahb_ready_i
add wave -noupdate /bench/dahb_resp_i
add wave -noupdate /bench/dahb_busreq_o
add wave -noupdate /bench/dahb_lock_o
add wave -noupdate /bench/iahb_clk_i
add wave -noupdate /bench/dahb_grant_i
add wave -noupdate /bench/iahb_rstn_i
add wave -noupdate /bench/iahb_addr_o
add wave -noupdate /bench/iahb_trans_o
add wave -noupdate /bench/iahb_write_o
add wave -noupdate /bench/iahb_size_o
add wave -noupdate /bench/iahb_burst_o
add wave -noupdate /bench/iahb_prot_o
add wave -noupdate /bench/iahb_wdata_o
add wave -noupdate /bench/iahb_rdata_i
add wave -noupdate /bench/iahb_ready_i
add wave -noupdate /bench/iahb_resp_i
add wave -noupdate /bench/iahb_busreq_o
add wave -noupdate /bench/iahb_lock_o
add wave -noupdate /bench/iahb_grant_i
add wave -noupdate /bench/dwb_dat_i
add wave -noupdate /bench/dwb_ack_i
add wave -noupdate /bench/dwb_err_i
add wave -noupdate /bench/dwb_rty_i
add wave -noupdate /bench/dwb_adr_o
add wave -noupdate /bench/dwb_dat_o
add wave -noupdate /bench/dwb_we_o
add wave -noupdate /bench/dwb_sel_o
add wave -noupdate /bench/dwb_stb_o
add wave -noupdate /bench/dwb_cyc_o
add wave -noupdate /bench/dwb_cti_o
add wave -noupdate /bench/dwb_bte_o
add wave -noupdate /bench/iwb_dat_i
add wave -noupdate /bench/iwb_ack_i
add wave -noupdate /bench/iwb_err_i
add wave -noupdate /bench/iwb_rty_i
add wave -noupdate /bench/iwb_adr_o
add wave -noupdate /bench/iwb_dat_o
add wave -noupdate /bench/iwb_we_o
add wave -noupdate /bench/iwb_sel_o
add wave -noupdate /bench/iwb_stb_o
add wave -noupdate /bench/iwb_cyc_o
add wave -noupdate /bench/iwb_cti_o
add wave -noupdate /bench/iwb_bte_o
add wave -noupdate /bench/pm_stall_i
add wave -noupdate /bench/pm_stalled_o
add wave -noupdate /bench/pm_event_o
add wave -noupdate /bench/du_clk_en_o
add wave -noupdate /bench/rf_clk_en_o
add wave -noupdate /bench/pm_fscale_o
add wave -noupdate /bench/pm_freq_i
add wave -noupdate /bench/pm_clmode_i
add wave -noupdate /bench/du_clk_en
add wave -noupdate /bench/rf_clk_en
add wave -noupdate /bench/idqmem_wdata
add wave -noupdate /bench/start_load
add wave -noupdate /bench/clk_load
add wave -noupdate /bench/clk_mux
add wave -noupdate /bench/load_done
add wave -noupdate /bench/initram_addr
add wave -noupdate /bench/initram_data
add wave -noupdate /bench/initram_byte_en
add wave -noupdate /bench/initram_stb
add wave -noupdate /bench/int_val
add wave -noupdate /bench/iqmem_stb
add wave -noupdate /bench/iqmem_we
add wave -noupdate /bench/iqmem_addr
add wave -noupdate /bench/iqmem_byte_en
add wave -noupdate /bench/iqmem_wdata
add wave -noupdate /bench/du_clk_i
add wave -noupdate /bench/rf_clk_i
add wave -noupdate /bench/ben_le_sel
add wave -noupdate /bench/addr_rom
add wave -noupdate /bench/data_rom
add wave -noupdate /bench/pm_clk_i
add wave -noupdate /bench/dahb_grant_i_nd
add wave -noupdate /bench/dahb_ready_i_nd
add wave -noupdate /bench/dahb_resp_i_nd
add wave -noupdate /bench/dahb_rdata_i_nd
add wave -noupdate /bench/u_initram32/state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {140 ps} 0}
configure wave -namecolwidth 178
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {508506298 ps} {508539458 ps}
